<a href="https://colab.research.google.com/github/KartikayBhardwaj-dev/Ai_lab/blob/main/ai_lab_week01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np
import pandas as pd

**Numpy Arrays**



In [4]:
# @title Dimension and shape
x = np.array([1, 2, 3])
print(f'Shape is dimension of  vectors: {x, x.shape}')
print(f'Dimension is how many features deos  vectors have: {x, x.ndim}')

M = np.array([
    [1, 2],
    [4, 5]

])

print(f'Shape is dimension of  Matrix: {M, M.shape}')
print(f'Dimension is how many features deos  Matrix have: {M, M.ndim}')



Shape is dimension of  vectors: (array([1, 2, 3]), (3,))
Dimension is how many features deos  vectors have: (array([1, 2, 3]), 1)
Shape is dimension of  Matrix: (array([[1, 2],
       [4, 5]]), (2, 2))
Dimension is how many features deos  Matrix have: (array([[1, 2],
       [4, 5]]), 2)


In [7]:
# @title Reshaping: matrix to vectors and vice - versa
x = np.array([1, 2, 3, 4, 5, 6])
M = x.reshape(3, 2)
M



array([[1, 2],
       [3, 4],
       [5, 6]])

-1 trick in reshaping we dont know the column part we can let numpy do that

reshape(3, -1)

In [9]:
M = np.array([
    [1, 2],
    [3, 4]
])
P = M.reshape(1, -1)
P

array([[1, 2, 3, 4]])

In [15]:
# @title Matrix Vector Addition
M = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
x = np.array([1, 2, 3])
print(f'it adds x to each row of matrix \n{M+x}')



it adds x to each row of matrix 
[[2 4 6]
 [5 7 9]]


In [16]:
# @title Advance Indexing -> we can give list of indices
x = np.array([1, 2, 3])
x[[1, 2]]

array([2, 3])

In [18]:
# @title Filtering particular values
x = np.array([1, 2, 3, 4, 54])
x[x > 40]


array([54])

**PANDAS**

In [28]:
# @title Creating DataFrame 1. From lists of lists , 2. From series objects, 3.  from dictionaries
print("1. From lists of lists")
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns = ["col1", "col2", "col3"], index = ['one', 'two', 'three'])
print(f"dataframe: \n {df} \n")
print(f'Values: \n \n{df.values}')

print("\n 2. From series objects ")
series_data = {'col1': pd.Series([1, 2, 3]),
               'col2': pd.Series([4, 5, 6]),}
df_Series = pd.DataFrame(series_data)
print(df_Series)

1. From lists of lists
dataframe: 
        col1  col2  col3
one       1     2     3
two       4     5     6
three     7     8     9 

Values: 
 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

 2. From series objects 
   col1  col2
0     1     4
1     2     5
2     3     6


In [36]:
# @title Loading datasets, 1. load data from csv file, 2. load from json file,  3. load from html file
print("1. Load from csv file")
df = pd.read_csv("/content/housing.csv")
print(df.info())
print("\n 3. Load from url")
url = 'https://en.wikipedia.org/wiki/List_of_highest-grossing_films'
df_url = pd.read_html(url)
print(df_url)

1. Load from csv file
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB
None

 3. Load from url


HTTPError: HTTP Error 403: Forbidden

In [37]:
# @title types of datatype columns, 1. int or float, 2. category or object and we need to convert category field to numeric to model train
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [56]:
# @title Selecting data, 1. Select Coloumns, 2. select rows, 3. Select Columns and rows, 4. Conditional selection, 5. Special selection Methods
print("1. Select Columns")
print(f"selecting by giving column name\n{df["longitude"]}")

print(f"\n 2. Select Rows by iloc  \n \n {df.iloc[0:3]}")
print(f"\n 3. Select Rows and Columns by iloc only takes indices not strings \n \n {df.iloc[0:3, 0:2]}")
print(f"\n 4. Select Rows and Columns by loc can take numeric indices only when indices deafalut integere otherwise no \n \n {df.loc[0:2, ['longitude', 'latitude']]}")
print(f"\n 5. Conditional selection \n {df[df['population'] > 1000]}")

1. Select Columns
selecting by giving column name
0       -122.23
1       -122.22
2       -122.24
3       -122.25
4       -122.25
          ...  
20635   -121.09
20636   -121.21
20637   -121.22
20638   -121.32
20639   -121.24
Name: longitude, Length: 20640, dtype: float64

 2. Select Rows by iloc  
 
    longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  

 3. Select Rows and Columns by iloc only takes indices not strings 
 
    longi